package me.prouge.sealedfluentbuilder.utils;

public enum Message {

    SELECTION_TITLE,
    ARRANGEMENT_TITLE,
    REQUIRED_FIELDS_ERROR,
    SELECTED_FIELDS_ERROR,
    REQUIRED_FIELDS_LABEL,
    OPTIONAL_FIELDS_LABEL,
    AVAILABLE_FIELDS_LABEL,
    BUTTON_UP_LABEL,
    BUTTON_DOWN_LABEL,

    ARRANGEMENT_RADIO_BUTTON_CONSTRUCTOR,
    ARRANGEMENT_RADIO_BUTTON_CONSTRUCTOR_WITH_BUILDER,
    ARRANGEMENT_RADIO_BUTTON_CONSTRUCTOR_WITH_SETTER,


}